source: .
destination: ./_site
url: https://mball.co
baseurl: ""
repository: cycomachead/cycomachead.github.io

title: Michael Ball
copy-start: 2011
copy-end: 2024
description: >
  Michael Ball is a lecturer in EECS and Data Science at UC Berkeley.
  This site contains a collection of photography and some blog posts.

keywords:
  - photography
  - Michael Ball
  - UC Berkeley
  - cycomachead
  - cs education
  - computer science
  - programming
  - travel
  - academia


# TODO: This comes from Academic Pages, update all settings+template
# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar: /assets/images/profile.jpg
  name: Michael Ball
  # bio: Lectuer at UC Berkeley, Software Engineer, Snap! and BJC developer, Photographer and Travel Agent
  location: San Francisco
  employer: UC Berkeley, Data Science & EECS
  uri: https://www.eecs.berkeley.edu/Faculty/Homepages/mball.html
  email: ball@berkeley.edu
  # Academic websites
  dblp: https://dblp.org/pid/175/6457.html
  googlescholar: https://scholar.google.com/citations?hl=en&user=UBJ4SvIAAAAJ
  orcid: https://orcid.org/0000-0002-7036-3902
  github: cycomachead
  flickr: cycomachead
  instagram: cycomachead
  keybase: # Username
  linkedin: /pub/michael-ball/43/18a/81/
  mastodon: https://hci.social/deck/@_mball_
  twitter: _mball_
  youtube: # Username

collections:
  pages:
    output: true


copy_to_dest:
  - source: node_modules/@fortawesome/fontawesome-free/webfonts/.
    target: assets/webfonts/
  # - source: node_modules/flag-icon-css/flags/.
  #   target: assets/flags/
navbar:
  title: Michael Ball
  pre_title:
    - title: Photography
      url: /photos
  post_title:
    - title: About
      url: /about
    - title: CV
      url: /cv
  options:
    search: false

# Sass/SCSS
sass:
  sass_dir: assets/scss/
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  load_paths:
    - node_modules/
  verbose: true



# Outputting
permalink: /:categories/:title/
paginate: 6
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

include:
  - .htaccess
  - files
  - assets
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Gemfile
  - LICENSE
  - README
  - Rakefile
  - node_modules
  - package.json
  - tmp
  - vendor
encoding: "utf-8"


markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
