source: .
destination: ./_site
url: https://mball.co
baseurl: ""

title: Michael Ball
copy-start: 2011
copy-end: 2024
description:

keywords:
  - photography
  - Michael Ball
  - UC Berkeley
  - cycomachead
  - cs education
  - computer science
  - programming
  - travel
  - academia


# TODO: This comes from Academic Pages, update all settings+template
# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar: "profile.png"
  name: Michael Ball
  pronouns: he/him
  bio: "Short biography for the left-hand sidebar"
  location: "San Francisco"
  employer: "UC Berkeley"
  uri: https://mball.co
  email: ball@berkeley.edu

  # Academic websites
  dblp: https://dblp.org/pid/175/6457.html
  ucberkeley:
  googlescholar: https://scholar.google.com/citations?hl=en&user=UBJ4SvIAAAAJ
  orcid: https://orcid.org/0000-0002-7036-3902
  # researchgate: # URL
  # impactstory: # URL

  github: cycomachead
  flickr: cycomachead
  instagram: cycomachead
  keybase: # Username
  linkedin: https://linkedin.com/pub/michael-ball/43/18a/81/
  mastodon: # URL
  twitter: _mball_
  youtube: # Username


# TODO: This legacy section needs to be removed...
flickr: cycomachead
github: cycomachead
instagram: cycomachead
linkedin: pub/michael-ball/43/18a/81/
twitter: _mball_

# Sass/SCSS
sass:
  sass_dir: assets/scss/
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  load_paths:
    - node_modules/
  verbose: true



# Outputting
permalink: /:categories/:title/
paginate: 6
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

include:
  - .htaccess
  - files
  - assets
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Gemfile
  - LICENSE
  - README
  - Rakefile
  - node_modules
  - package.json
  - tmp
  - vendor
encoding: "utf-8"


# Conversion
markdown: CommonMark
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
