source: .
destination: ./_site
url: https://mball.co
baseurl: ""
repository: cycomachead/cycomachead.github.io

title: Michael Ball
copy-start: 2011
copy-end: 2024
description:

keywords:
  - photography
  - Michael Ball
  - UC Berkeley
  - cycomachead
  - cs education
  - computer science
  - programming
  - travel
  - academia


# TODO: This comes from Academic Pages, update all settings+template
# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "profile.png"
  name             : Michael Ball
  pronouns         : he/him
  bio              : "Short biography for the left-hand sidebar"
  location         : "San Francisco"
  employer         : "UC Berkeley"
  uri              : https://mball.co
  email            : ball@berkeley.edu

  # Academic websites
  # TODO -- pages to add to template:
  # dblp
  # ucberkeley
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  # impactstory      : # URL
  orcid            : "http://orcid.org/yourorcidurl"
  # researchgate     : # URL

  github           : "cycomachead"
  flickr           : # Username
  keybase          : # Username
  linkedin         : # Username
  mastodon         : # URL
  twitter          : # Username for X / Twitter
  youtube          : # Username


# TODO: This legacy section needs to be removed...
flickr: cycomachead
github: cycomachead
instagram: cycomachead
linkedin: pub/michael-ball/43/18a/81/
twitter: _mball_

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 6
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

include:
  - .htaccess
  - _pages
  - files
  - assets
  - images
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
encoding: "utf-8"


# Conversion
markdown: CommonMark
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
