# frozen_string_literal: true

require 'jekyll'
require 'pathname'

# Tools to build / compile the Jekyll site and extract the sitemap.
#
# Adapted from https://github.com/berkeley-cdss/berkeley-class-site

# Build the Jekyll config for the site under test.
# Override with RSPEC_CONFIG_FILE to test an alternate build.
def read_site_config
  # NOTE: Config keys must be strings and thus use => style hashes.
  overrides = { 'sass' => { 'quiet_deps' => true } }
  config_file = ENV.fetch('RSPEC_CONFIG_FILE', nil)
  overrides['config'] = config_file if config_file
  Jekyll.configuration(overrides)
end

# A constant rather than an @ivar: site_config is called from inside
# Rack::Builder's instance_eval'd block, where an instance variable would
# belong to the builder and the config would be parsed a second time.
SITE_CONFIG = read_site_config.freeze

def site_config
  SITE_CONFIG
end

# The site's Sass imports Bootstrap and Font Awesome straight out of
# `node_modules/`, and `_plugins/copy_to_dest.rb` copies the Font Awesome
# webfonts into `_site`. Both fail confusingly if `npm install` hasn't run.
def check_node_modules!
  return if Dir.exist?(File.join(site_config['source'], 'node_modules'))

  raise 'node_modules/ is missing. Run `npm install` before `bundle exec rspec`.'
end

def build_jekyll_site!
  check_node_modules!
  @site = Jekyll::Site.new(site_config)
  @site.process
end

def load_sitemap
  # Requires build_jekyll_site! to have been called first.
  # sitemap.xml is generated by the jekyll-sitemap plugin.
  sitemap_path = File.expand_path('sitemap.xml', site_config['destination'])
  raise "#{sitemap_path} not found. Did the Jekyll build succeed?" unless File.exist?(sitemap_path)

  sitemap_text = File.read(sitemap_path)
  sitemap_links = sitemap_text.scan(%r{<loc>.+</loc>})
  sitemap_links.filter_map do |link|
    link = link.gsub("<loc>#{site_config['url']}", '').gsub('</loc>', '')
    # Skip non-html pages.
    # (FUTURE?) Are there other pages that should be audited for accessibility?
    # (e.g. PDFs, documents. They'd need a different checker.)
    next unless link.end_with?('.html') || link.end_with?('/')

    link
  end.sort
end

# Start a local Rack server
# https://nts.strzibny.name/how-to-test-static-sites-with-rspec-capybara-and-webkit/
class StaticSite
  attr_reader :root, :server, :build_dir

  def initialize(root)
    @root = root
    @server = Rack::Files.new(root)
    # '_site' — the destination directory, relative to the repo root. The
    # config value may be relative ('./_site') or absolute.
    dest = File.expand_path(site_config['destination'], site_config['source'])
    @build_dir = "/#{Pathname.new(dest).relative_path_from(root)}"
  end

  def call(env)
    # Strip the /baseurl prefix, which is present in all URLs but not in the
    # file system. Note this site's baseurl is "", and gsub('', '/') would
    # cheerfully insert a slash between every character of the path.
    baseurl = site_config['baseurl'].to_s
    request_path = env['PATH_INFO']
    request_path = request_path.delete_prefix(baseurl) unless baseurl.empty?
    path = "#{build_dir}#{request_path}"

    env['PATH_INFO'] = if path.end_with?('/') && exists?("#{path}index.html")
                         "#{path}index.html"
                       elsif !exists?(path) && exists?("#{path}.html")
                         "#{path}.html"
                       else
                         path
                       end

    server.call(env)
  end

  def exists?(path)
    File.exist?(File.join(root, path))
  end
end
